# Generated by Django 2.1.2 on 2018-10-30 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_user_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='sex',
            new_name='gender',
        ),
    ]
